apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: http://lyour-customer-image:latest  # Replace with your image and tag
          ports:
            - containerPort: 8001
          # Add volume mounts and resources as needed
          resources:
            limits:
              memory: "512Mi"  # Adjust the memory limit as needed
              cpu: "0.5"        # Adjust the CPU limit as needed
