name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  code-Scan:
    runs-on: ubuntu-latest
    name: Code-Scan
    steps:
      - uses: actions/checkout@v3
      - uses: ./sonarqube
      
  build:
    runs-on: ubuntu-latest
    needs: code-Scan
    name: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./docker/docker.yml

  sca:
    runs-on: ubuntu-latest
    needs: build
    name: SCA
    steps:
      - uses: actions/checkout@v3
      - uses: ./sca/sca.yml
  
  sast:
    runs-on: ubuntu-latest
    needs: build
    name: SAST
    steps:
      - uses: actions/checkout@v3
      - uses: ./sast/sast/yml

  tivy-scan:
    runs-on: ubuntu-latest
    needs: build
    name: Trivy
    steps:
      - uses: actions/checkout@v3
      - uses: ./trivy-scan/trivy-scan.yml

  dast:
    runs-on: ubuntu-latest
    needs: build
    name: DAST
    steps:
      - uses: actions/checkout@v3
      - uses: ./dast/dast.yml
  