name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Code-Scan:
    name: Code-Scan
    uses: ./.github/workflows/sonarqube.yml
    secrets: inherit

  Build:
    name: Build
    uses: ./.github/workflows/docker.yml
    secrets: inherit #https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit

  sca:
    needs: Build
    name: SCA
    uses: ./.github/workflows/sca.yml
    secrets: inherit
  
  sast:
    needs: Build
    name: SAST
    uses: ./.github/workflows/sast.yml
    secrets: inherit
  