name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # code-Scan:
  #   runs-on: ubuntu-latest
  #   name: Code-Scan
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./sonarqube
  # code-scan:
  #   name: Code-Scan
  #   uses: ./.github/workflows/sonarqube.yml
  #   secrets: inherit

  # build:
  #   needs: code-scan
  #   name: Build
  #   uses: ./.github/workflows/docker.yml
  #   secrets: inherit

  sca:
    # needs: build
    name: SCA
    uses: ./.github/workflows/sca.yml
    secrets: inherit
  
  # sast:
  #   needs: build
  #   name: SAST
  #   uses: ./.github/workflows/sast.yml
  #   secrets: inherit

  tivy-scan:
    # needs: build
    name: Trivy
    uses: ./.github/workflows/trivy-scan.yml
    secrets: inherit

  dast:
    # needs: build
    name: DAST
    uses: ./.github/workflows/dast.yml
    secrets: inherit
    with:
      image-tag: ${{ needs.docker.outputs.image-tag }}
  