name: Trivy scan
on:
  workflow_call:
    inputs:
      image-tag:
        type: string
        description: 'The name of the docker image to scan'
        required: true

jobs:
  Trviy-scan:
    name: trivy-scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build an image from Dockerfile
        run: docker build -t pirabanjan/buy-it-customer-service:${{ inputs.image-tag }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'pirabanjan/buy-it-customer-service:${{ inputs.image-tag }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'LOW,MEDIUM,HIGH,CRITICAL'
      - name: Save Trivy scan report as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: trivy-report
          path: /github/workspace/trivy_report.txt
